<?xml version="1.0" encoding="utf-8"?><Database Name="C:\DATA\EAP\EMP\EMPLOYEEDBFIX.MDF" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-6SKF56J;Initial Catalog=C:\DATA\EAP\EMP\EMPLOYEEDBFIX.MDF;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="C__DATA_EAP_EMP_EMPLOYEEDBFIX_MDFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="empID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>